// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package version

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Info contains versioning information. how we'll want to distribute that information.
type Info struct {
	BuildDate    string `pulumi:"buildDate"`
	Compiler     string `pulumi:"compiler"`
	GitCommit    string `pulumi:"gitCommit"`
	GitTreeState string `pulumi:"gitTreeState"`
	GitVersion   string `pulumi:"gitVersion"`
	GoVersion    string `pulumi:"goVersion"`
	Major        string `pulumi:"major"`
	Minor        string `pulumi:"minor"`
	Platform     string `pulumi:"platform"`
}

func init() {
	pulumi.RegisterOutputType(InfoOutput{})
}
