# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from ... import _utilities, _tables
from ... import core as _core
from ... import meta as _meta

__all__ = [
    'JobArgs',
    'JobConditionArgs',
    'JobSpecArgs',
    'JobStatusArgs',
]

@pulumi.input_type
class JobArgs:
    api_version: Optional[pulumi.Input[str]] = pulumi.input_property("apiVersion")
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[pulumi.Input[str]] = pulumi.input_property("kind")
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']] = pulumi.input_property("metadata")
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Optional[pulumi.Input['JobSpecArgs']] = pulumi.input_property("spec")
    """
    Specification of the desired behavior of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    """
    status: Optional[pulumi.Input['JobStatusArgs']] = pulumi.input_property("status")
    """
    Current status of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, api_version: Optional[pulumi.Input[str]] = None, kind: Optional[pulumi.Input[str]] = None, metadata: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']] = None, spec: Optional[pulumi.Input['JobSpecArgs']] = None, status: Optional[pulumi.Input['JobStatusArgs']] = None) -> None:
        """
        Job represents the configuration of a single job.

        This resource waits until its status is ready before registering success
        for create/update, and populating output properties from the current state of the resource.
        The following conditions are used to determine whether the resource creation has
        succeeded or failed:

        1. The Job's '.status.startTime' is set, which indicates that the Job has started running.
        2. The Job's '.status.conditions' has a status of type 'Complete', and a 'status' set
           to 'True'.
        3. The Job's '.status.conditions' do not have a status of type 'Failed', with a
        	'status' set to 'True'. If this condition is set, we should fail the Job immediately.

        If the Job has not reached a Ready state after 10 minutes, it will
        time out and mark the resource update as Failed. You can override the default timeout value
        by setting the 'customTimeouts' option on the resource.
        :param pulumi.Input[str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input['JobSpecArgs'] spec: Specification of the desired behavior of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
        :param pulumi.Input['JobStatusArgs'] status: Current status of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
        """
        __self__.api_version = 'batch/v1'
        __self__.kind = 'Job'
        __self__.metadata = metadata
        __self__.spec = spec
        __self__.status = status

@pulumi.input_type
class JobConditionArgs:
    status: pulumi.Input[str] = pulumi.input_property("status")
    """
    Status of the condition, one of True, False, Unknown.
    """
    type: pulumi.Input[str] = pulumi.input_property("type")
    """
    Type of job condition, Complete or Failed.
    """
    last_probe_time: Optional[pulumi.Input[str]] = pulumi.input_property("lastProbeTime")
    """
    Last time the condition was checked.
    """
    last_transition_time: Optional[pulumi.Input[str]] = pulumi.input_property("lastTransitionTime")
    """
    Last time the condition transit from one status to another.
    """
    message: Optional[pulumi.Input[str]] = pulumi.input_property("message")
    """
    Human readable message indicating details about last transition.
    """
    reason: Optional[pulumi.Input[str]] = pulumi.input_property("reason")
    """
    (brief) reason for the condition's last transition.
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, status: pulumi.Input[str], type: pulumi.Input[str], last_probe_time: Optional[pulumi.Input[str]] = None, last_transition_time: Optional[pulumi.Input[str]] = None, message: Optional[pulumi.Input[str]] = None, reason: Optional[pulumi.Input[str]] = None) -> None:
        """
        JobCondition describes current state of a job.
        :param pulumi.Input[str] status: Status of the condition, one of True, False, Unknown.
        :param pulumi.Input[str] type: Type of job condition, Complete or Failed.
        :param pulumi.Input[str] last_probe_time: Last time the condition was checked.
        :param pulumi.Input[str] last_transition_time: Last time the condition transit from one status to another.
        :param pulumi.Input[str] message: Human readable message indicating details about last transition.
        :param pulumi.Input[str] reason: (brief) reason for the condition's last transition.
        """
        __self__.status = status
        __self__.type = type
        __self__.last_probe_time = last_probe_time
        __self__.last_transition_time = last_transition_time
        __self__.message = message
        __self__.reason = reason

@pulumi.input_type
class JobSpecArgs:
    template: pulumi.Input['_core.v1.PodTemplateSpecArgs'] = pulumi.input_property("template")
    """
    Describes the pod that will be created when executing a job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    """
    active_deadline_seconds: Optional[pulumi.Input[float]] = pulumi.input_property("activeDeadlineSeconds")
    """
    Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    """
    backoff_limit: Optional[pulumi.Input[float]] = pulumi.input_property("backoffLimit")
    """
    Specifies the number of retries before marking this job failed. Defaults to 6
    """
    completions: Optional[pulumi.Input[float]] = pulumi.input_property("completions")
    """
    Specifies the desired number of successfully finished pods the job should be run with.  Setting to nil means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    """
    manual_selector: Optional[pulumi.Input[bool]] = pulumi.input_property("manualSelector")
    """
    manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector
    """
    parallelism: Optional[pulumi.Input[float]] = pulumi.input_property("parallelism")
    """
    Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    """
    selector: Optional[pulumi.Input['_meta.v1.LabelSelectorArgs']] = pulumi.input_property("selector")
    """
    A label query over pods that should match the pod count. Normally, the system sets this field for you. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
    """
    ttl_seconds_after_finished: Optional[pulumi.Input[float]] = pulumi.input_property("ttlSecondsAfterFinished")
    """
    ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes. This field is alpha-level and is only honored by servers that enable the TTLAfterFinished feature.
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, template: pulumi.Input['_core.v1.PodTemplateSpecArgs'], active_deadline_seconds: Optional[pulumi.Input[float]] = None, backoff_limit: Optional[pulumi.Input[float]] = None, completions: Optional[pulumi.Input[float]] = None, manual_selector: Optional[pulumi.Input[bool]] = None, parallelism: Optional[pulumi.Input[float]] = None, selector: Optional[pulumi.Input['_meta.v1.LabelSelectorArgs']] = None, ttl_seconds_after_finished: Optional[pulumi.Input[float]] = None) -> None:
        """
        JobSpec describes how the job execution will look like.
        :param pulumi.Input['_core.v1.PodTemplateSpecArgs'] template: Describes the pod that will be created when executing a job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
        :param pulumi.Input[float] active_deadline_seconds: Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
        :param pulumi.Input[float] backoff_limit: Specifies the number of retries before marking this job failed. Defaults to 6
        :param pulumi.Input[float] completions: Specifies the desired number of successfully finished pods the job should be run with.  Setting to nil means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
        :param pulumi.Input[bool] manual_selector: manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector
        :param pulumi.Input[float] parallelism: Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
        :param pulumi.Input['_meta.v1.LabelSelectorArgs'] selector: A label query over pods that should match the pod count. Normally, the system sets this field for you. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
        :param pulumi.Input[float] ttl_seconds_after_finished: ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes. This field is alpha-level and is only honored by servers that enable the TTLAfterFinished feature.
        """
        __self__.template = template
        __self__.active_deadline_seconds = active_deadline_seconds
        __self__.backoff_limit = backoff_limit
        __self__.completions = completions
        __self__.manual_selector = manual_selector
        __self__.parallelism = parallelism
        __self__.selector = selector
        __self__.ttl_seconds_after_finished = ttl_seconds_after_finished

@pulumi.input_type
class JobStatusArgs:
    active: Optional[pulumi.Input[float]] = pulumi.input_property("active")
    """
    The number of actively running pods.
    """
    completion_time: Optional[pulumi.Input[str]] = pulumi.input_property("completionTime")
    """
    Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
    """
    conditions: Optional[pulumi.Input[List[pulumi.Input['JobConditionArgs']]]] = pulumi.input_property("conditions")
    """
    The latest available observations of an object's current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
    """
    failed: Optional[pulumi.Input[float]] = pulumi.input_property("failed")
    """
    The number of pods which reached phase Failed.
    """
    start_time: Optional[pulumi.Input[str]] = pulumi.input_property("startTime")
    """
    Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
    """
    succeeded: Optional[pulumi.Input[float]] = pulumi.input_property("succeeded")
    """
    The number of pods which reached phase Succeeded.
    """

    # pylint: disable=no-self-argument
    def __init__(__self__, *, active: Optional[pulumi.Input[float]] = None, completion_time: Optional[pulumi.Input[str]] = None, conditions: Optional[pulumi.Input[List[pulumi.Input['JobConditionArgs']]]] = None, failed: Optional[pulumi.Input[float]] = None, start_time: Optional[pulumi.Input[str]] = None, succeeded: Optional[pulumi.Input[float]] = None) -> None:
        """
        JobStatus represents the current state of a Job.
        :param pulumi.Input[float] active: The number of actively running pods.
        :param pulumi.Input[str] completion_time: Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
        :param pulumi.Input[List[pulumi.Input['JobConditionArgs']]] conditions: The latest available observations of an object's current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
        :param pulumi.Input[float] failed: The number of pods which reached phase Failed.
        :param pulumi.Input[str] start_time: Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
        :param pulumi.Input[float] succeeded: The number of pods which reached phase Succeeded.
        """
        __self__.active = active
        __self__.completion_time = completion_time
        __self__.conditions = conditions
        __self__.failed = failed
        __self__.start_time = start_time
        __self__.succeeded = succeeded

