// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

export namespace admissionregistration {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace apiextensions {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace apiregistration {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace apps {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }

    export namespace v1beta2 {
    }
}

export namespace auditregistration {
    export namespace v1alpha1 {
    }
}

export namespace authentication {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace authorization {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace autoscaling {
    export namespace v1 {
    }

    export namespace v2beta1 {
    }

    export namespace v2beta2 {
    }
}

export namespace batch {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }

    export namespace v2alpha1 {
    }
}

export namespace certificates {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace coordination {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace core {
    export namespace v1 {
    }
}

export namespace discovery {
    export namespace v1beta1 {
    }
}

export namespace events {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace extensions {
    export namespace v1beta1 {
    }
}

export namespace flowcontrol {
    export namespace v1alpha1 {
    }
}

export namespace meta {
    export namespace v1 {
    }
}

export namespace networking {
    export namespace v1 {
    }

    export namespace v1beta1 {
    }
}

export namespace node {
    export namespace v1alpha1 {
    }

    export namespace v1beta1 {
    }
}

export namespace pkg {
    export namespace version {
    }
}

export namespace policy {
    export namespace v1beta1 {
    }
}

export namespace rbac {
    export namespace v1 {
    }

    export namespace v1alpha1 {
    }

    export namespace v1beta1 {
    }
}

export namespace scheduling {
    export namespace v1 {
    }

    export namespace v1alpha1 {
    }

    export namespace v1beta1 {
    }
}

export namespace settings {
    export namespace v1alpha1 {
    }
}

export namespace storage {
    export namespace v1 {
    }

    export namespace v1alpha1 {
    }

    export namespace v1beta1 {
    }
}
